### ISSUE TITLE
Corridor Generation

### ISSUE THREAD

**Issue by JimboSwaggins** [SloopLiztmin/DungeonGen#1]
Corridors all connect to only one room - that is, every room only will draw corridors to a single room, usually multiple times.

**Comment by jakeisnt** [comment]
got it.
this was intentional, wanted to test basic connections before I built it out to every node/assigned only one connection between two nodes

**Comment by jakeisnt** [comment]
fixed. only one room connects to but it looks good doing so. done for the night.
another issue:
- terribly organized code (didn't organize in proper methods of node class, works fine but can probably be rearranged/rewritten to be more intuitive/efficient)
- only one room hosts a first node thus far. would be cool to jump to every node created and have it branch out but that seems hard. iteration through every room probably easier
